metadata:
  name: pov-bedrock-hub-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    nethopper.io/objectID: 6638b91a40fd508444602463
    nethopper.io/cloudID: 6638af3d40fd508444602291
spec:
  source:
    path: guestbook
    chart: ""
    repoURL: https://github.com/nethopper2/argocd-example-apps.git
    targetRevision: main
  destination:
    namespace: default
    name: ""
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
apiVersion: argoproj.io/v1alpha1
kind: Application
