metadata:
  name: pov-bedrock-edge-1-istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    nethopper.io/objectID: 6639f5ade48854cb1708aaf5
    nethopper.io/cloudID: 6638af7340fd50844460229e
spec:
  source:
    path: ""
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.22.0-beta.1
    helm:
      valueFiles: null
      values: >-
        labels:
          istio: ingressgateway
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
  destination:
    namespace: istio-ingress
    name: ""
    server: https://nh-kapi-pov-bedrock-edge-1:8080
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
apiVersion: argoproj.io/v1alpha1
kind: Application
