metadata:
  name: pov-bedrock-edge-2-spinnaker
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    nethopper.io/objectID: 663a424a150316ee7a26fa60
    nethopper.io/cloudID: 6638af5fc5cd46f1322b8a90
spec:
  source:
    path: deploy/spinnaker/spinnaker
    chart: ""
    repoURL: https://github.com/nethopper2/pov-bedrock.git
    targetRevision: main
  destination:
    namespace: spinnaker-operator
    name: ""
    server: https://nh-kapi-pov-bedrock-edge-2:8080
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
apiVersion: argoproj.io/v1alpha1
kind: Application
